name: Security scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  trivy-fs:
    name: Trivy FS scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trivy FS scan (repository)
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          exit-code: '1'
          vulnerability-type: 'os,library'

  trivy-image:
    name: Trivy Docker image scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./src/Api
          file: ./src/Api/Dockerfile
          platforms: linux/amd64
          tags: api:latest
          outputs: type=docker,dest=/tmp/api-image.tar

      - name: Load image
        run: docker load -i /tmp/api-image.tar

      - name: Trivy Image scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: api:latest
          ignore-unfixed: true
          format: table
          exit-code: '1'
          vulnerability-type: 'os,library'

         