name: Security scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Scansione file e dipendenze (SCA + IaC)
      - name: Trivy FS scan (repository)
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs # FS scan ? analizza il repository (codice, pacchetti NuGet, Dockerfile, YAML) per vulnerabilità.
          ignore-unfixed: true
          format: table
          exit-code: '1'
          vulnerability-type: 'os,library'

      # Build immagine Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: ./src/Api
          file: ./src/Api/Dockerfile
          platforms: linux/amd64
          outputs: type=docker,dest=/tmp/api-image.tar

      - name: Load image
        run: docker load -i /tmp/api-image.tar

      # Scansione immagine Docker
      - name: Trivy Image scan #Image scan ? costruisce l’immagine Docker e la scansiona.
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: api:latest
          ignore-unfixed: true
          format: table
          exit-code: '1'
          vulnerability-type: 'os,library'

         